controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    integral_sliding_mode_controller:
      type: velocity_controllers/IntegralSlidingModeController

    thruster_allocation_matrix_controller:
      type: thruster_allocation_matrix_controller/ThrusterAllocationMatrixController

    left_thruster_prop_controller:
      type: thruster_controllers/GazeboPassthroughController

    right_thruster_prop_controller:
      type: thruster_controllers/GazeboPassthroughController

    vert_thruster_prop_controller:
      type: thruster_controllers/GazeboPassthroughController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

integral_sliding_mode_controller:
  ros__parameters:
    use_external_measured_states: true
    reference_controller: thruster_allocation_matrix_controller
    gains:
      rho: 20.0
      lambda: 200.0
      Kp: [10.0, 10.0, 6.0, 3.0, 6.0, 10.0]

thruster_allocation_matrix_controller:
  ros__parameters:
    thrusters:
      - left_thruster_prop_joint
      - right_thruster_prop_joint
      - vert_thruster_prop_joint
    reference_controllers:
      - left_thruster_prop_controller
      - right_thruster_prop_controller
      - vert_thruster_prop_controller
    tam:
      x:  [      1.0,      1.0, 0.0]
      y:  [      0.0,      0.0, 0.0]
      z:  [      0.0,      0.0, 1.0]
      rx: [      0.0,      0.0, 0.0]
      ry: [      0.0,      0.0, 0.0]
      rz: [-0.012331, 0.012331, 0.0]
      # x:  [-0.707,  -0.707,   0.707,  0.707,      0.0,     0.0,      0.0,     0.0]
      # y:  [ 0.707,  -0.707,   0.707, -0.707,      0.0,     0.0,      0.0,     0.0]
      # z:  [   0.0,     0.0,     0.0,    0.0,      1.0,     1.0,      1.0,     1.0]
      # rx: [   0.0,     0.0,     0.0,    0.0, -0.21805, 0.21805, -0.21805, 0.21805]
      # ry: [   0.0,     0.0,     0.0,    0.0,    -0.12,   -0.12,     0.12,    0.12]
      # rz: [0.1888, -0.1888, -0.1888, 0.1888,      0.0,     0.0,      0.0 ,    0.0]

left_thruster_prop_controller:
  ros__parameters:
    thruster: left_thruster_prop_joint
    topic: /model/sisid_debug/joint/left_thruster_prop_joint/cmd_thrust

right_thruster_prop_controller:
  ros__parameters:
    thruster: right_thruster_prop_joint
    topic: /model/sisid_debug/joint/right_thruster_prop_joint/cmd_thrust

vert_thruster_prop_controller:
  ros__parameters:
    thruster: vert_thruster_prop_joint
    topic: /model/sisid_debug/joint/vert_thruster_prop_joint/cmd_thrust
